# SPDX-FileCopyrightText: 2026 Cadex Authors
# SPDX-License-Identifier: LGPL-2.1-or-later

"""What the accepted assembly is made of, as a file in the project (ADR-236).

The first of the headless review calls the charter asks for: *list the parts
of an assembly with catalog ids*. It reads ``inspect scope="inventory"`` —
the engine's join of every component to the output it places, that output's
catalog row and the pose the solver settled on — and renders it as a domain
doc under the project's ``docs/``.

**Rendered, not just printed.** The review step of the lifecycle walk is read
by an agent on its *next* visit, and the thing an agent reads on a visit is
the project's documents (ADR-193). A table checked into the project's own
repository outlives the run that produced it; a JSON blob on stdout does not.
The machine-readable form is one ``inspect`` call away for anyone who wants
it, so this writes one file rather than two.

The file is **generated and overwritten**, like the clearance report, which
is why it says so in its own first line. Other domain docs are written by
hand or by a turn, and this must never quietly eat one of those.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping, Sequence

from .project_docs import DOMAIN_DOCS_DIRNAME


INVENTORY_DOC_NAME = "inventory.md"

_HEADER = """# Inventory — {name}

<!-- Generated by `cadex inventory`. Overwritten on every run; do not edit. -->

Accepted revision `{revision}`{assembly}. {count} component(s).

| component | places | catalog | position (mm) | volume (mm³) |
|---|---|---|---|---|
"""


class InventoryError(RuntimeError):
    """The engine could not answer with an accepted inventory."""


def _cell(text: Any) -> str:
    value = str(text if text is not None else "")
    return value.replace("|", "\\|") or "—"


def _position(row: Mapping[str, Any]) -> str:
    placement = row.get("placement") or {}
    position = placement.get("position_mm")
    if not isinstance(position, (list, tuple)) or len(position) != 3:
        return "—"
    return ", ".join(f"{float(value):.3f}" for value in position)


def _volume(row: Mapping[str, Any]) -> str:
    facts = row.get("source_facts") or {}
    volume = facts.get("volume_mm3")
    if not isinstance(volume, (int, float)):
        return "—"
    return f"{float(volume):.3f}"


def _catalog(row: Mapping[str, Any]) -> str:
    catalog = row.get("catalog")
    if isinstance(catalog, Mapping):
        return "{:s} `{:s}`".format(
            str(catalog.get("family") or ""), str(catalog.get("part_number") or "")
        )
    # Not a catalog part, and the engine can say what it was cut from
    # (ADR-381): a modified purchase reads differently from a printed part.
    came_off = row.get("catalog_derived_from")
    if isinstance(came_off, Mapping):
        return "cut from {:s} `{:s}`".format(
            str(came_off.get("family") or ""), str(came_off.get("part_number") or "")
        )
    return "—"


def render_inventory(value: Mapping[str, Any], *, name: str) -> str:
    """The markdown a project keeps for one accepted assembly."""

    components: Sequence[Mapping[str, Any]] = [
        row for row in list(value.get("components") or []) if isinstance(row, Mapping)
    ]
    assembly = str(value.get("assembly") or "")
    text = _HEADER.format(
        name=name,
        revision=str(value.get("revision") or "")[:12],
        assembly=f", assembly `{assembly}`" if assembly else "",
        count=len(components),
    )
    if not assembly:
        text += "\nInventory unavailable: no published assembly.\n"
    for row in components:
        text += "| `{:s}` | `{:s}` | {:s} | {:s} | {:s} |\n".format(
            _cell(row.get("component")),
            _cell(row.get("source_output")),
            _catalog(row),
            _position(row),
            _volume(row),
        )
    counts = dict(value.get("catalog_counts") or {})
    if counts:
        text += "\n## Catalog roll-up\n\n"
        for key in sorted(counts):
            text += f"- `{key}` × {int(counts[key])}\n"
    uncatalogued = [str(item) for item in list(value.get("uncatalogued_sources") or [])]
    if uncatalogued:
        text += (
            "\n## Not from the catalog\n\n"
            "Outputs modelled by hand rather than by a `lib.*` generator:\n\n"
        )
        came_off = {
            str(row.get("source_output") or ""): row
            for row in list(value.get("derived_catalog_sources") or [])
            if isinstance(row, Mapping)
        }
        for item in sorted(uncatalogued):
            row = came_off.get(item)
            if row is None:
                text += f"- `{item}`\n"
            else:
                text += "- `{:s}` — cut from `{:s}/{:s}`, a purchased part this script modified\n".format(
                    item,
                    str(row.get("family") or ""),
                    str(row.get("part_number") or ""),
                )
    return text


#: The engine caps `inspect` at 50 per page and shrinks it further to stay
#: inside the 32 KiB result limit, so the chain is followed rather than
#: assumed — an assembly of forty bolts is more than one page.
_PAGE_LIMIT = 50


def _ask(client: Any, arguments: Mapping[str, Any]) -> dict[str, Any]:
    reply = client.request("inspect", dict(arguments))
    if reply.get("ok") is not True:
        raise InventoryError(
            f"inspect scope={arguments.get('scope')} failed: "
            + str(reply.get("error") or reply.get("failure_code") or reply)
        )
    return dict(reply)


def _read_path(client: Any, base: Mapping[str, Any], path: str) -> Any:
    """Join bounded pages and recursively resolve their preview pointers."""

    def expand(value: Any) -> Any:
        if isinstance(value, Mapping):
            pointer = value.get("inspect_path")
            if isinstance(pointer, str) and value.get("type") in {"object", "array", "string"}:
                return _read_path(client, base, pointer)
            return {key: expand(item) for key, item in value.items()}
        if isinstance(value, list):
            return [expand(item) for item in value]
        return value

    result = None
    offset = 0
    while True:
        reply = _ask(client, {**base, "path": path, "offset": offset, "limit": _PAGE_LIMIT})
        value = expand(reply.get("value"))
        if offset == 0:
            result = value
        elif isinstance(result, dict):
            result.update(value)
        elif isinstance(result, list):
            result.extend(value)
        else:
            result += value  # Strings are paged by character offset.
        next_offset = (reply.get("page") or {}).get("next_offset")
        if not isinstance(next_offset, int) or next_offset <= offset:
            return result
        offset = next_offset


#: Where the inventory block's counts come from, said in the block itself
#: so the agent reading it cannot mistake it for the script's own claim
#: about which parts it took from the catalog.
INVENTORY_SOURCE = (
    "the published inventory of the accepted revision (inspect "
    "scope=inventory): one row per placed assembly component, with a catalog "
    "row only where the placed output is what a lib.* generator built. Not "
    "the script's stdout. Advisory, not a fit check: a printed part is "
    "expected here, a purchased part is not."
)


def inventory_summary(value: Any) -> dict[str, Any]:
    """The catalog identity of a build as its reply carries it (ADR-362).

    ``value`` is an ``inspect scope=inventory`` value. The block is the
    component count, how many components place a catalog part, the catalog
    roll-up by ``family/part_number``, and the name of **every** placed
    output that no ``lib.*`` generator built as-is -- a hand-modelled
    bracket, but also a servo body the script drilled after taking it from
    the catalog, since a cut catalog body is no longer the catalog part.
    The block is advisory: it names no failure and refuses nothing. What
    ``derived_catalog_sources`` names the ones the engine can prove are a
    modified purchase rather than a printed part -- the catalog body their
    base was cut from (ADR-381). What
    it removes is the blind spot ot7's F5 measured over four turns, an
    agent that reported every purchased part as catalog hardware while
    the published inventory listed its servos and horns as uncatalogued,
    because nothing in its reply carried catalog identity. ``available``
    is false when the accepted revision publishes no assembly.
    """

    if not isinstance(value, Mapping):
        value = {}
    components = [
        row for row in list(value.get("components") or []) if isinstance(row, Mapping)
    ]
    counts = {
        str(key): int(count)
        for key, count in dict(value.get("catalog_counts") or {}).items()
    }
    catalogued = sum(counts.values())
    uncatalogued = sorted({
        str(item) for item in list(value.get("uncatalogued_sources") or [])
    })
    derived = [
        {
            "source_output": str(row.get("source_output") or ""),
            "family": str(row.get("family") or ""),
            "part_number": str(row.get("part_number") or ""),
        }
        for row in list(value.get("derived_catalog_sources") or [])
        if isinstance(row, Mapping)
    ]
    derived.sort(key=lambda row: row["source_output"])
    assembly = str(value.get("assembly") or "")
    summary: dict[str, Any] = {
        "available": bool(assembly),
        "source": INVENTORY_SOURCE,
        "revision": str(value.get("revision") or ""),
        "assembly": assembly,
        "component_count": len(components),
        "catalogued_count": catalogued,
        "uncatalogued_count": max(len(components) - catalogued, 0),
        "catalog_counts": dict(sorted(counts.items())),
        "uncatalogued_sources": uncatalogued,
        "derived_catalog_sources": derived,
    }
    if not assembly:
        summary["note"] = (
            "No published assembly: catalog identity is read per placed "
            "assembly component, and this revision places none."
        )
    elif uncatalogued:
        note = (
            "Each name under uncatalogued_sources is a placed output no lib.* "
            "generator built as-is. Printed parts belong here. A purchased "
            "part listed here has lost its catalog identity -- usually "
            "because the script cut, drilled or re-clocked the catalog body "
            "-- and is not catalog hardware whatever the script prints."
        )
        if derived:
            note += (
                " derived_catalog_sources names the ones the engine can "
                "prove are exactly that: "
                + ", ".join(
                    "{:s} (cut from {:s}/{:s})".format(
                        row["source_output"], row["family"], row["part_number"]
                    )
                    for row in derived
                )
                + ". Place the untouched catalog body as the component and "
                "put the cut in the printed part that receives it."
            )
        summary["note"] = note
    return summary


def read_inventory_summary(client: Any, *, target: str = "") -> dict[str, Any]:
    """Read the published inventory scope, every page, and summarise it."""

    return inventory_summary(read_inventory(client, target=target))


def read_inventory(client: Any, *, target: str = "") -> dict[str, Any]:
    """Read all inventory pages, including summaries and previewed row fields."""

    base: dict[str, Any] = {"scope": "inventory"}
    if target:
        base["target"] = target
    value = _read_path(client, base, "")
    if not isinstance(value, Mapping):
        raise InventoryError("inspect scope=inventory returned no value.")
    if value.get("ok") is False:
        raise InventoryError(str(value.get("error") or "no accepted revision."))
    result = dict(value)
    result["component_count"] = len(result.get("components") or [])
    return result


def write_inventory(
    client: Any, root: Path | str, *, target: str = ""
) -> tuple[Path, dict[str, Any]]:
    """Ask the engine, render, and land the file. Returns the path and value."""

    value = read_inventory(client, target=target)
    base = Path(root)
    directory = base / DOMAIN_DOCS_DIRNAME
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / INVENTORY_DOC_NAME
    path.write_text(
        render_inventory(value, name=base.resolve().name or "project"),
        encoding="utf-8",
    )
    return path, value
