# SPDX-FileCopyrightText: 2026 Cadex Authors
# SPDX-License-Identifier: LGPL-2.1-or-later

"""What the accepted assembly is made of, as a file in the project (ADR-236).

The first of the headless review calls the charter asks for: *list the parts
of an assembly with catalog ids*. It reads ``inspect scope="inventory"`` —
the engine's join of every component to the output it places, that output's
catalog row and the pose the solver settled on — and renders it as a domain
doc under the project's ``docs/``.

**Rendered, not just printed.** The review step of the lifecycle walk is read
by an agent on its *next* visit, and the thing an agent reads on a visit is
the project's documents (ADR-193). A table checked into the project's own
repository outlives the run that produced it; a JSON blob on stdout does not.
The machine-readable form is one ``inspect`` call away for anyone who wants
it, so this writes one file rather than two.

The file is **generated and overwritten** — the only doc under ``docs/`` that
is, which is why it says so in its own first line. Everything else there is
written by hand or by a turn, and this must never quietly eat one of those.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping, Sequence

from .project_docs import DOMAIN_DOCS_DIRNAME


INVENTORY_DOC_NAME = "inventory.md"

_HEADER = """# Inventory — {name}

<!-- Generated by `cadex inventory`. Overwritten on every run; do not edit. -->

Accepted revision `{revision}`{assembly}. {count} component(s).

| component | places | catalog | position (mm) | volume (mm³) |
|---|---|---|---|---|
"""


class InventoryError(RuntimeError):
    """The engine could not answer, or answered with no assembly."""


def _cell(text: Any) -> str:
    value = str(text if text is not None else "")
    return value.replace("|", "\\|") or "—"


def _position(row: Mapping[str, Any]) -> str:
    placement = row.get("placement") or {}
    position = placement.get("position_mm")
    if not isinstance(position, (list, tuple)) or len(position) != 3:
        return "—"
    return ", ".join(f"{float(value):.3f}" for value in position)


def _volume(row: Mapping[str, Any]) -> str:
    facts = row.get("source_facts") or {}
    volume = facts.get("volume_mm3")
    if not isinstance(volume, (int, float)):
        return "—"
    return f"{float(volume):.3f}"


def _catalog(row: Mapping[str, Any]) -> str:
    catalog = row.get("catalog")
    if not isinstance(catalog, Mapping):
        return "—"
    return "{:s} `{:s}`".format(
        str(catalog.get("family") or ""), str(catalog.get("part_number") or "")
    )


def render_inventory(value: Mapping[str, Any], *, name: str) -> str:
    """The markdown a project keeps for one accepted assembly."""

    components: Sequence[Mapping[str, Any]] = [
        row for row in list(value.get("components") or []) if isinstance(row, Mapping)
    ]
    assembly = str(value.get("assembly") or "")
    text = _HEADER.format(
        name=name,
        revision=str(value.get("revision") or "")[:12],
        assembly=f", assembly `{assembly}`" if assembly else "",
        count=len(components),
    )
    for row in components:
        text += "| `{:s}` | `{:s}` | {:s} | {:s} | {:s} |\n".format(
            _cell(row.get("component")),
            _cell(row.get("source_output")),
            _catalog(row),
            _position(row),
            _volume(row),
        )
    counts = dict(value.get("catalog_counts") or {})
    if counts:
        text += "\n## Catalog roll-up\n\n"
        for key in sorted(counts):
            text += f"- `{key}` × {int(counts[key])}\n"
    uncatalogued = [str(item) for item in list(value.get("uncatalogued_sources") or [])]
    if uncatalogued:
        text += (
            "\n## Not from the catalog\n\n"
            "Outputs modelled by hand rather than by a `lib.*` generator:\n\n"
        )
        for item in sorted(uncatalogued):
            text += f"- `{item}`\n"
    return text


#: The engine caps `inspect` at 50 per page and shrinks it further to stay
#: inside the 32 KiB result limit, so the chain is followed rather than
#: assumed — an assembly of forty bolts is more than one page.
_PAGE_LIMIT = 50


def _ask(client: Any, arguments: Mapping[str, Any]) -> dict[str, Any]:
    reply = client.request("inspect", dict(arguments))
    if reply.get("ok") is not True:
        raise InventoryError(
            "inspect scope=inventory failed: "
            + str(reply.get("error") or reply.get("failure_code") or reply)
        )
    return dict(reply)


def read_inventory(client: Any, *, target: str = "") -> dict[str, Any]:
    """The whole inventory, however many pages its component list is.

    The summary comes back whole; ``components`` arrives as a preview stub
    the moment the list outgrows the per-key preview budget, which is the
    ordinary ``inspect`` contract and the reason this pages ``/components``
    rather than trusting the first reply.
    """

    base: dict[str, Any] = {"scope": "inventory"}
    if target:
        base["target"] = target
    value = _ask(client, base).get("value")
    if not isinstance(value, Mapping):
        raise InventoryError("inspect scope=inventory returned no value.")
    if value.get("ok") is False:
        raise InventoryError(str(value.get("error") or "no accepted revision."))
    result = dict(value)
    components: list[dict[str, Any]] = []
    offset = 0
    while True:
        reply = _ask(
            client,
            {**base, "path": "/components", "offset": offset, "limit": _PAGE_LIMIT},
        )
        page_value = reply.get("value")
        if isinstance(page_value, list):
            components.extend(
                dict(item) for item in page_value if isinstance(item, Mapping)
            )
        next_offset = (reply.get("page") or {}).get("next_offset")
        if not isinstance(next_offset, int) or next_offset <= offset:
            break
        offset = next_offset
    result["components"] = components
    result["component_count"] = len(components)
    return result


def write_inventory(
    client: Any, root: Path | str, *, target: str = ""
) -> tuple[Path, dict[str, Any]]:
    """Ask the engine, render, and land the file. Returns the path and value."""

    value = read_inventory(client, target=target)
    base = Path(root)
    directory = base / DOMAIN_DOCS_DIRNAME
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / INVENTORY_DOC_NAME
    path.write_text(
        render_inventory(value, name=base.resolve().name or "project"),
        encoding="utf-8",
    )
    return path, value
